name: Automatically create v[x] / latest tags

on:
  workflow_dispatch:
  release:
    types: [published, edited]

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@v2
        env:
          GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
        with:
          publish_latest_tag: true
